### ISSUE TITLE
从模板创建

### ISSUE THREAD

**Issue by aboutmydreams** [tencentyun/serverless-demo#12]
Downloading code
Initializing node.js environment
Installing plugins
Installing dependencies
Processing serverless config files
Deploying serverless project
serverless deploy --debug
Initializing...
Action: "deploy" - Stage: "dev" - App: "doc-helper" - Instance: "flask--CY8AFEB-"
the code will be uploaded to https://sp-ins-prod-1300963013.cos.ap-guangzhou.myqcloud.com/cb7d1d69-45fa-4a55-a798-5134a622962b.zip?q-sign-algorithm=sha1&q-ak=AKID1qcBe1cVaOwSmtn67y7pJJIAVj4jftBE&q-sign-time=1610565272;1610565872&q-key-time=1610565272;1610565872&q-header-list=&q-url-param-list=&q-signature=209f777d77ad31f2edabbb1832894e50049817b0
Uploading...
Deploying...

 Error: 函数状态异常, 未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。
    at new TypeError (/var/user/node_modules/tencent-component-toolkit/src/utils/error.js:2:15)
    at Scf.isOperationalStatus (/var/user/node_modules/tencent-component-toolkit/src/modules/scf/index.js:460:11)

25s › flask--CY8AFEB- › 函数状态异常, 未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。 

  帮助文档: https://cloud.tencent.com/document/product/1154/39270 
  获取支持: https://cloud.tencent.com/act/event/Online_service 
  问答社区: https://cloud.tencent.com/developer/ask 

script returned exit code 1

**Comment by alfredhuang211** [comment]
是使用的哪个模板？

**Comment by aboutmydreams** [comment]
> 是使用的哪个模板？

Instance: "flask--CY8AFEB-"
